name: climb_logger
description: Your climbing logbook.

publish_to: 'none'

version: 1.1.3+39
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  cloud_firestore: ^3.1.5
  freezed_annotation: ^1.1.0
  json_annotation: ^4.4.0
  flutter_bloc: ^8.0.0
  loading_indicator: ^3.0.2
  build_runner: ^2.1.7
  google_sign_in: ^5.2.1
  intl: ^0.17.0
  number_to_words: ^1.0.0
  syncfusion_flutter_charts: ^19.4.40
  google_mobile_ads: ^1.0.1
  in_app_purchase: ^2.0.1
  csv: ^5.0.1
  path_provider: ^2.0.8
  open_file: ^3.2.1
  flutter_colorpicker: ^1.0.3
  sign_in_with_apple: ^3.3.0
  sentry_flutter: ^6.2.2
  file_picker: ^4.3.3
  excel: ^2.0.0-null-safety-3
  mockito: ^5.1.0
  package_info_plus: ^1.0.6
  uuid: ^3.0.6
  flutter_beep: ^1.0.0
  wakelock: ^0.6.1+2
  flutter_mailer: ^2.0.1
  table_calendar: ^3.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  freezed: ^1.1.0
  json_serializable: ^6.1.3
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  image_path_android: "assets/icon.png"
  image_path_ios: "assets/icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon_foreground.png"
flutter:
  uses-material-design: true
  assets:
    - assets/